name = "ai-chat-assistant"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_SESSIONS"
class_name = "ChatSession"

[[migrations]]
tag = "v1"
new_classes = ["ChatSession"]

[env.production]
name = "ai-chat-assistant-prod"

[env.staging]
name = "ai-chat-assistant-staging"
